# Generated by Django 4.0.5 on 2022-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('festival_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('festival_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'festival',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FestivalImg',
            fields=[
                ('festival_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'festival_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FestivalInfo',
            fields=[
                ('festival_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('organizer_info', models.CharField(blank=True, max_length=100, null=True)),
                ('performance_time', models.TextField(blank=True, null=True)),
                ('place_of_event', models.TextField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.TextField(blank=True, null=True)),
                ('detail_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'festival_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
                ('search', models.BigIntegerField(db_column='Search')),
            ],
            options={
                'db_table': 'Hotspot',
                'managed': False,
            },
        ),
    ]
