# Generated by Django 4.0.5 on 2022-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
                ('search', models.BigIntegerField(db_column='Search')),
            ],
            options={
                'db_table': 'Hotspot',
                'managed': False,
            },
        ),
    ]
